# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HRvnELZXFDemdyx8-fB2_1mIh78ZOGYF
"""

# Install necessary libraries
!pip install nltk spacy

# Import required modules
import nltk
import spacy
from nltk.tokenize import word_tokenize, sent_tokenize

# Download the 'punkt_tab' resource for sentence tokenization
nltk.download('punkt_tab') # This line downloads the missing data
nltk.download('punkt')

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# Sample text
text = "Google was founded by Larry Page and Sergey Brin in September 1998."

# Tokenization using NLTK
print("Sentence Tokenization:")
print(sent_tokenize(text))

print("\nWord Tokenization:")
print(word_tokenize(text))

# NLP processing using spaCy
doc = nlp(text)

# Named Entity Recognition (NER)
print("\nNamed Entities:")
for ent in doc.ents:
    print(f"{ent.text} - {ent.label_}")

# POS Tagging
print("\nPart-of-Speech (POS) Tagging:")
for token in doc:
    print(f"{token.text} - {token.pos_}")

